import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Car Service App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ka">
      <body className={inter.className}>
        <Header />

        <div className="container px-8 sm:px-0 mx-auto">
          {children}
        </div>
      
      </body>
    </html>
  )
}
